In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
x+2

array([3, 4, 5, 6])

In [4]:
y = [[1,2,3,4],[5,6,7,8]]
x+y

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [6]:
# Element wise Multiplication : Hadamard product *
A = np.array([[1,2],[3,4]])
B = np.array([[0,2],[3,2]])
print(A*B)
print(np.dot(A,B))

[[0 4]
 [9 8]]
[[ 6  6]
 [12 14]]
