In [1]:
import numpy as np

In [8]:
x = np.array([3,4])

lp2 = np.linalg.norm(x)
print(lp2)

lp1 = np.linalg.norm(x,ord = 1)
print(lp1)

lp3 = np.linalg.norm(x,ord = 3)
print(lp3)

lpinf = np.linalg.norm(x,ord = np.inf)
print(lpinf)
# here big vale

5.0
7.0
4.497941445275415
4.0


In [10]:
# Determinant
A = np.array([[1,2],[3,4]])
np.linalg.det(A)

-2.0000000000000004

In [14]:
# Inverse
Ainv = np.linalg.inv(A)
print(np.dot(A,Ainv))

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [18]:
# Whene determinant is 0 so that matrix cant be inverted
# sudo inverse
A = np.array([[6,8],[3,4]])
pinv = np.linalg.pinv(A)
print(pinv)
print(np.dot(A,pinv))

[[0.048 0.024]
 [0.064 0.032]]
[[0.8 0.4]
 [0.4 0.2]]


In [20]:
# Solve a system of Linear Equations
a = np.array([[2,3],[3,1]])
b = np.array([8,5])

In [21]:
np.linalg.solve(a,b)

array([1., 2.])