In [2]:
import numpy as np

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = np.arange(10) + 5
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
c = np.arange(1,9)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
d = np.arange(1 , 5 , 2)
d

array([1, 3])

In [13]:
# want to shuffle elements of a
np.random.shuffle(a)
a

array([9, 4, 6, 5, 0, 2, 1, 8, 3, 7])

In [17]:
# want to generate array of random numbers
# returns values from a Standard Normal Distribution
a = np.random.rand(2,3)
a

array([[0.10496486, 0.00679071, 0.85457122],
       [0.57740601, 0.91548691, 0.01123466]])

In [18]:
a = np.random.randint(5,10,3)
a

array([6, 9, 5])

In [23]:
# Randomly one elemenent from array
element = np.random.choice([1,2, 4,5,6,8])
element

2

In [25]:
# state fix karna
np.random.seed(1)