In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4],[7,6,2,0]])

In [4]:
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [5]:
print(np.min(a))

0


In [8]:
print(np.min(a , axis = 0))
print(np.min(a , axis = 1))

[1 2 2 0]
[1 0]


In [10]:
print(np.mean(a))

3.125


In [11]:
print(a.mean())

3.125


In [12]:
a.mean(axis = 1)

array([2.5 , 3.75])

In [13]:
a.mean(axis = 0)

array([4. , 4. , 2.5, 2. ])

In [14]:
c = np.array([1 ,2 , 34, 6 ,9])

In [15]:
print(np.median(c))

6.0


In [18]:
# Average is Weighted Mean
w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

print(np.mean(c))

11.733333333333333
10.4


In [19]:
w = np.array([1,1,1,1,1])
print(np.average(c,weights = w))

print(np.mean(c))

10.4
10.4


In [23]:
# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u) ** 2))
print(myStd)

s = np.std(c)
print(s)

print(myStd ** 2)
print(np.var(c))

12.142487389328434
12.142487389328434
147.44000000000003
147.44000000000003
