### Working with Numpy - for mathematical operations

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [8]:
b[0][0]

1

In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
c[1][1]

5

In [16]:
# Create Zeros , Ones , Custom array
a = np.zeros((3,3))
print(a)

b = np.ones((2,3))
print(b)

c = np.full((3,2),5)
print(c)

# Identity Matrix
d = np.eye(4)
print(d)

# Random Matrix 
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.03757249 0.43670053 0.72664809]
 [0.50284692 0.91265214 0.58790734]]


In [17]:
randomMatrix[:,1]

array([0.43670053, 0.91265214])

In [19]:
randomMatrix[1,1:3] = 1
randomMatrix

array([[0.03757249, 0.43670053, 0.72664809],
       [0.50284692, 1.        , 1.        ]])

In [25]:
## set some rows and columns with any values
z = np.zeros((3,3) , dtype = np.int64)
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [26]:
# Datatype
z.dtype

dtype('int64')

In [32]:
# Mathematical Operations 
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))
print(np.sqrt(y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [33]:
# Matrix Multiplication and Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [44]:
# Multiplication of Vectors
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [35]:
print(sum(a))

10


In [36]:
np.sum(a)

10

In [39]:
print(x)

[[1 2]
 [3 4]]


In [40]:
np.sum(x,axis = 0)

array([4, 6])

In [41]:
np.sum(x,axis = 1)

array([3, 7])

In [45]:
# Stacking of Arrays
print(a)
print(b)
b = b ** 2
print(b)

[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]


In [46]:
np.stack((a,b),axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [51]:
a = np.stack((a,b),axis = 0)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [53]:
# Reshape a Numpy Array
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
