In [38]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.naive_bayes import CategoricalNB

In [2]:
# loading data
data = pd.read_csv("Naive Bayes Data.txt")

In [3]:
# seeing data
data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [4]:
# shape of data
data.shape

(8124, 23)

In [5]:
# starting 5 rows of data
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [6]:
# now we will split label from data - in class column we have label
labels = data['class']
print(labels.shape)
print(labels)

(8124,)
0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 8124, dtype: object


In [8]:
# printing type of label
print(type(labels))

<class 'pandas.core.series.Series'>


In [9]:
# changing series to numpy array
labels = labels.values
type(labels)

numpy.ndarray

In [10]:
# Now we have labels in differnt array 
# Now we can drop labels from our data
X = data.drop(['class'] , axis = 1)  # axis = 1 for column
print(type(X))
# change X in numpy array
X = X.values
print(type(X))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [12]:
# Now we have only one data so we will split it in two parts - train and test data
# import library
from sklearn.model_selection import train_test_split

In [15]:
# splitting data
X_train , X_test , Y_train , Y_test = train_test_split(X,labels,test_size = 0.2 , random_state = 10)

In [16]:
# printing shapes of splitted data
print(X_train.shape , X_test.shape)
print(Y_train.shape , Y_test.shape)

(6499, 22) (1625, 22)
(6499,) (1625,)


In [19]:
# importing library for encoding
from sklearn.preprocessing import LabelEncoder

In [20]:
# making a function for label encoding of all columns
def label_encoding(d) :
    # result array is for new Encoded data
    result = np.empty(d.shape)
    # l_encoders is used to store what type of encoding is done
    l_encoders = []
    # running loop for all columns
    for i in range(d.shape[1]) :
        # making le as a instance of labelEncoder
        le = LabelEncoder()
        # encoded data column wise daal rahe h in new data  result
        result[:,i] = le.fit_transform(d[:,i])
        # appending ki kis type ki encoding hui h
        l_encoders.append(le)
    return l_encoders , result

In [21]:
# Now we will do label encoding of training dtaa
les , x_train = label_encoding(X_train)
print(x_train.shape)
print(x_train)

(6499, 22)
[[5. 3. 2. ... 2. 4. 0.]
 [5. 2. 4. ... 7. 4. 0.]
 [5. 3. 4. ... 7. 4. 4.]
 ...
 [2. 3. 3. ... 1. 5. 1.]
 [3. 2. 3. ... 7. 2. 1.]
 [2. 2. 8. ... 2. 0. 1.]]


In [22]:
# Now we will check labeling
print(np.unique(x_train[:,0]))
print(np.unique(X_train[:,0]))
# labellling is done alphabetically

[0. 1. 2. 3. 4. 5.]
['b' 'c' 'f' 'k' 's' 'x']


In [24]:
# Now print les
print(len(les))

22


In [25]:
for i , le in enumerate(les) :
    print(i,le.classes_)

0 ['b' 'c' 'f' 'k' 's' 'x']
1 ['f' 'g' 's' 'y']
2 ['b' 'c' 'e' 'g' 'n' 'p' 'r' 'u' 'w' 'y']
3 ['f' 't']
4 ['a' 'c' 'f' 'l' 'm' 'n' 'p' 's' 'y']
5 ['a' 'f']
6 ['c' 'w']
7 ['b' 'n']
8 ['b' 'e' 'g' 'h' 'k' 'n' 'o' 'p' 'r' 'u' 'w' 'y']
9 ['e' 't']
10 ['?' 'b' 'c' 'e' 'r']
11 ['f' 'k' 's' 'y']
12 ['f' 'k' 's' 'y']
13 ['b' 'c' 'e' 'g' 'n' 'o' 'p' 'w' 'y']
14 ['b' 'c' 'e' 'g' 'n' 'o' 'p' 'w' 'y']
15 ['p']
16 ['n' 'o' 'w' 'y']
17 ['n' 'o' 't']
18 ['e' 'f' 'l' 'n' 'p']
19 ['b' 'h' 'k' 'n' 'o' 'r' 'u' 'w' 'y']
20 ['a' 'c' 'n' 's' 'v' 'y']
21 ['d' 'g' 'l' 'm' 'p' 'u' 'w']


In [32]:
# Now as we know we cant use the same function of label encoder for X_test 
# as we will only transform , not fit
x_test = np.empty(X_test.shape)
for i in range(X_test.shape[1]) :
    le = les[i]
    x_test[:,i] = le.transform(X_test[:,i])
print(x_test)
print(X_test)

[[5. 3. 8. ... 2. 2. 1.]
 [2. 2. 4. ... 2. 3. 5.]
 [5. 2. 8. ... 2. 3. 1.]
 ...
 [2. 3. 9. ... 1. 4. 0.]
 [5. 0. 3. ... 3. 4. 0.]
 [5. 3. 4. ... 3. 5. 0.]]
[['x' 'y' 'w' ... 'k' 'n' 'g']
 ['f' 's' 'n' ... 'k' 's' 'u']
 ['x' 's' 'w' ... 'k' 's' 'g']
 ...
 ['f' 'y' 'y' ... 'h' 'v' 'd']
 ['x' 'f' 'g' ... 'n' 'v' 'd']
 ['x' 'y' 'n' ... 'n' 'y' 'd']]


In [34]:
# Now we will encode our labels
print(np.unique(labels))

['e' 'p']


In [35]:
# make dictionarya nd use it for label encoding of labels
map_ = {'e' : 0 , 'p' : 1}
y_train = np.array([map_[el] for el in Y_train])
y_test = np.array([map_[el] for el in Y_test])
print(y_train)
print(y_test)
# Label encoding is done for all the things

[0 1 1 ... 1 0 0]
[0 1 0 ... 1 1 0]


In [ ]:
class NaiveBayes_Categorical :
    
    def fit(self , X , y) :
        # compute priors of each class
        self.class_priors = []
        