In [37]:
!pip install nltk

In [38]:
import nltk
#NLTK allows us to download dataset
# NLTK Corpus for text datasets

In [39]:
#for downloading datasets 
nltk.download()
# it will open a graphical interface and allows us to download any dataset

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [40]:
# i am have downloaded with brown dataset
# now import that dataset
from nltk.corpus import brown

In [41]:
# This brown data has came from 500 sources
# test data has sentences then words
# there are differnt genre present in this dataset

In [42]:
# we want to see what all categories are present in our dataset
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [43]:
# want to see how many categories in total are present
len(brown.categories())

15

In [44]:
# want to see words in this dataset in total
words = brown.words()
print(len(words))
print(words[:10])
# these words are total including all the categories

1161192
['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of']


In [45]:
# Now we want to know how many words are there in one particular category
words1 = brown.words(categories = 'adventure')
print(len(words1))

69342


In [46]:
# Now we want to know how many words are there in each category
categories = brown.categories()
for cat in categories :
    print(cat , len(brown.words(categories = cat)))

adventure 69342
belles_lettres 173096
editorial 61604
fiction 68488
government 70117
hobbies 82345
humor 21695
learned 181888
lore 110299
mystery 57169
news 100554
religion 39399
reviews 40704
romance 70022
science_fiction 14470


In [47]:
# now want to see sentences
brown.sents(categories ='adventure')
# we will get an 2D array in which every row has elements of that sentence
# number of rows = no of sentences

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]

In [48]:
# Now we want to make whole para from data
sentences = brown.sents(categories = 'adventure')
text = ""
for sentence in sentences :
    for word in sentence :
        text += word + " "
print(text)

Dan Morgan told himself he would forget Ann Turner . He was well rid of her . He certainly didn't want a wife who was fickle as Ann . If he had married her , he'd have been asking for trouble . But all of this was rationalization . Sometimes he woke up in the middle of the night thinking of Ann , and then could not get back to sleep . His plans and dreams had revolved around her so much and for so long that now he felt as if he had nothing . The easiest thing would be to sell out to Al Budd and leave the country , but there was a stubborn streak in him that wouldn't allow it . The best antidote for the bitterness and disappointment that poisoned him was hard work . He found that if he was tired enough at night , he went to sleep simply because he was too exhausted to stay awake . Each day he found himself thinking less often of Ann ; ; each day the hurt was a little duller , a little less poignant . He had plenty of work to do . Because the summer was unusually dry and hot , the spring

In [49]:
# Now to run an algorithm we need to convert text to numbers so we use nltk
# 1) Tokenization - breaking a text in tokens
#     in brown dataset we already get tokenized data but otherwise we need to do it manually
from nltk.tokenize import word_tokenize , sent_tokenize , RegexpTokenizer

In [50]:
text

"Dan Morgan told himself he would forget Ann Turner . He was well rid of her . He certainly didn't want a wife who was fickle as Ann . If he had married her , he'd have been asking for trouble . But all of this was rationalization . Sometimes he woke up in the middle of the night thinking of Ann , and then could not get back to sleep . His plans and dreams had revolved around her so much and for so long that now he felt as if he had nothing . The easiest thing would be to sell out to Al Budd and leave the country , but there was a stubborn streak in him that wouldn't allow it . The best antidote for the bitterness and disappointment that poisoned him was hard work . He found that if he was tired enough at night , he went to sleep simply because he was too exhausted to stay awake . Each day he found himself thinking less often of Ann ; ; each day the hurt was a little duller , a little less poignant . He had plenty of work to do . Because the summer was unusually dry and hot , the sprin

In [51]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\prach/Documents/Github/Data-Science-Live-
[nltk_data]     Master-Course-With-Python/Mam Practice...
[nltk_data]   Package punkt is already up-to-date!


True

In [52]:
# break data in sentences
sentences = sent_tokenize(text)
print(len(sentences))
print(sentences)
# got a link where each element is a sentence

4899
['Dan Morgan told himself he would forget Ann Turner .', 'He was well rid of her .', "He certainly didn't want a wife who was fickle as Ann .", "If he had married her , he'd have been asking for trouble .", 'But all of this was rationalization .', 'Sometimes he woke up in the middle of the night thinking of Ann , and then could not get back to sleep .', 'His plans and dreams had revolved around her so much and for so long that now he felt as if he had nothing .', "The easiest thing would be to sell out to Al Budd and leave the country , but there was a stubborn streak in him that wouldn't allow it .", 'The best antidote for the bitterness and disappointment that poisoned him was hard work .', 'He found that if he was tired enough at night , he went to sleep simply because he was too exhausted to stay awake .', 'Each day he found himself thinking less often of Ann ; ; each day the hurt was a little duller , a little less poignant .', 'He had plenty of work to do .', 'Because the su

In [53]:
words = word_tokenize(text)
print(len(words))
print(words)
# got a list of all words 1D

70650
['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.', 'He', 'was', 'well', 'rid', 'of', 'her', '.', 'He', 'certainly', 'did', "n't", 'want', 'a', 'wife', 'who', 'was', 'fickle', 'as', 'Ann', '.', 'If', 'he', 'had', 'married', 'her', ',', 'he', "'d", 'have', 'been', 'asking', 'for', 'trouble', '.', 'But', 'all', 'of', 'this', 'was', 'rationalization', '.', 'Sometimes', 'he', 'woke', 'up', 'in', 'the', 'middle', 'of', 'the', 'night', 'thinking', 'of', 'Ann', ',', 'and', 'then', 'could', 'not', 'get', 'back', 'to', 'sleep', '.', 'His', 'plans', 'and', 'dreams', 'had', 'revolved', 'around', 'her', 'so', 'much', 'and', 'for', 'so', 'long', 'that', 'now', 'he', 'felt', 'as', 'if', 'he', 'had', 'nothing', '.', 'The', 'easiest', 'thing', 'would', 'be', 'to', 'sell', 'out', 'to', 'Al', 'Budd', 'and', 'leave', 'the', 'country', ',', 'but', 'there', 'was', 'a', 'stubborn', 'streak', 'in', 'him', 'that', 'would', "n't", 'allow', 'it', '.', 'The', 'best', 'antido

In [54]:
import numpy as np

In [55]:
# we cant use split always as we can only use one separator
sample_text = text
sample_text = np.array(sample_text.split())
print(sample_text)

['Dan' 'Morgan' 'told' ... "''" '!' '!']


In [56]:
# Regexp Tokenizer - use this for expression
re = RegexpTokenizer(pattern="[A-Za-z]+")
sample_text = "I like movies , and mangoes, There are 40,000 people in that - hall"
re.tokenize(sample_text)
# now e got data in which there is no puntuation and no numbers 
# only alphabets are there

['I',
 'like',
 'movies',
 'and',
 'mangoes',
 'There',
 'are',
 'people',
 'in',
 'that',
 'hall']

In [57]:
# 2) Removal of Stopwords - removal of words which are common and will not help in classifying 
#      we will remove the useless words and use only useful words for classification
#      we can get a question - we need to tell the genre of a sentence
#      Examples of unnecessary words are - There , is , am , are , a , the 

In [58]:
from nltk.corpus import stopwords

In [59]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\prach/Documents/Github/Data-Science-Live-
[nltk_data]     Master-Course-With-Python/Mam Practice...
[nltk_data]   Package stopwords is already up-to-date!


True

In [60]:
# now want to see words in english that are stopwards
stop_words = stopwords.words('English')
print(len(stop_words))


179


In [61]:
print(stop_words)
# here we will get a list

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [62]:
print(*stop_words)
# here we will get a string
# * is used to change a list to string with " " as separator

i me my myself we our ours ourselves you you're you've you'll you'd your yours yourself yourselves he him his himself she she's her hers herself it it's its itself they them their theirs themselves what which who whom this that that'll these those am is are was were be been being have has had having do does did doing a an the and but if or because as until while of at by for with about against between into through during before after above below to from up down in out on off over under again further then once here there when where why how all any both each few more most other some such no nor not only own same so than too very s t can will just don don't should should've now d ll m o re ve y ain aren aren't couldn couldn't didn didn't doesn doesn't hadn hadn't hasn hasn't haven haven't isn isn't ma mightn mightn't mustn mustn't needn needn't shan shan't shouldn shouldn't wasn wasn't weren weren't won won't wouldn wouldn't


In [63]:
from nltk.corpus import stopwords


In [64]:
# want to see stopwords of french
print(stopwords.words('french'))
nltk.download('stopwords')

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aur

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\prach/Documents/Github/Data-Science-Live-
[nltk_data]     Master-Course-With-Python/Mam Practice...
[nltk_data]   Package stopwords is already up-to-date!


True

In [79]:
# now we know what words we need to remove from our data
words = re.tokenize(text)
print(words[:100])

['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', 'He', 'was', 'well', 'rid', 'of', 'her', 'He', 'certainly', 'didn', 't', 'want', 'a', 'wife', 'who', 'was', 'fickle', 'as', 'Ann', 'If', 'he', 'had', 'married', 'her', 'he', 'd', 'have', 'been', 'asking', 'for', 'trouble', 'But', 'all', 'of', 'this', 'was', 'rationalization', 'Sometimes', 'he', 'woke', 'up', 'in', 'the', 'middle', 'of', 'the', 'night', 'thinking', 'of', 'Ann', 'and', 'then', 'could', 'not', 'get', 'back', 'to', 'sleep', 'His', 'plans', 'and', 'dreams', 'had', 'revolved', 'around', 'her', 'so', 'much', 'and', 'for', 'so', 'long', 'that', 'now', 'he', 'felt', 'as', 'if', 'he', 'had', 'nothing', 'The', 'easiest', 'thing', 'would', 'be', 'to', 'sell', 'out', 'to', 'Al', 'Budd']


In [80]:
# make a function for removing stop words
def remove_stopwords(words , sw) :
    useful_words =[]
    for word in words :
        if word.lower() not in sw:
            useful_words.append(word)
    return useful_words


In [81]:
# now we call call the function
useful_words = remove_stopwords(words , stop_words)
print(len(useful_words))
print(useful_words)


29586
['Dan', 'Morgan', 'told', 'would', 'forget', 'Ann', 'Turner', 'well', 'rid', 'certainly', 'want', 'wife', 'fickle', 'Ann', 'married', 'asking', 'trouble', 'rationalization', 'Sometimes', 'woke', 'middle', 'night', 'thinking', 'Ann', 'could', 'get', 'back', 'sleep', 'plans', 'dreams', 'revolved', 'around', 'much', 'long', 'felt', 'nothing', 'easiest', 'thing', 'would', 'sell', 'Al', 'Budd', 'leave', 'country', 'stubborn', 'streak', 'allow', 'best', 'antidote', 'bitterness', 'disappointment', 'poisoned', 'hard', 'work', 'found', 'tired', 'enough', 'night', 'went', 'sleep', 'simply', 'exhausted', 'stay', 'awake', 'day', 'found', 'thinking', 'less', 'often', 'Ann', 'day', 'hurt', 'little', 'duller', 'little', 'less', 'poignant', 'plenty', 'work', 'summer', 'unusually', 'dry', 'hot', 'spring', 'produced', 'smaller', 'stream', 'ordinary', 'years', 'grass', 'meadows', 'came', 'fast', 'warm', 'weather', 'could', 'afford', 'lose', 'drop', 'precious', 'water', 'spent', 'waking', 'hours', '

In [139]:
# 3) Lemmetization / Stemming
#      we have different words who have root word same so change everey word in root and remove unique
from nltk.stem import PorterStemmer , SnowballStemmer , LancasterStemmer
ps = PorterStemmer()

In [83]:
ps.stem("revolved")

'revolv'

In [84]:
ps.stem('learning')

'learn'

In [85]:
ps.stem('establishment')

'establish'

In [86]:
# making a function for stemming
# we can only pass a single word so we need to make a function
def stemming(words , stemmer) :
    stemmed = [];
    for word in words :
        stemmed.append(stemmer.stem(word))
    return stemmed

In [87]:
# call function
stemmed_words = stemming(useful_words , ps)
print(len(stemmed_words))
print(stemmed_words)

29586
['dan', 'morgan', 'told', 'would', 'forget', 'ann', 'turner', 'well', 'rid', 'certainli', 'want', 'wife', 'fickl', 'ann', 'marri', 'ask', 'troubl', 'ration', 'sometim', 'woke', 'middl', 'night', 'think', 'ann', 'could', 'get', 'back', 'sleep', 'plan', 'dream', 'revolv', 'around', 'much', 'long', 'felt', 'noth', 'easiest', 'thing', 'would', 'sell', 'al', 'budd', 'leav', 'countri', 'stubborn', 'streak', 'allow', 'best', 'antidot', 'bitter', 'disappoint', 'poison', 'hard', 'work', 'found', 'tire', 'enough', 'night', 'went', 'sleep', 'simpli', 'exhaust', 'stay', 'awak', 'day', 'found', 'think', 'less', 'often', 'ann', 'day', 'hurt', 'littl', 'duller', 'littl', 'less', 'poignant', 'plenti', 'work', 'summer', 'unusu', 'dri', 'hot', 'spring', 'produc', 'smaller', 'stream', 'ordinari', 'year', 'grass', 'meadow', 'came', 'fast', 'warm', 'weather', 'could', 'afford', 'lose', 'drop', 'preciou', 'water', 'spent', 'wake', 'hour', 'along', 'ditch', 'meadow', 'idea', 'much', 'time', 'budd', 'wo

In [88]:
# now as we can see we have root words but some words are repeated so we only want unique words
unique_words = set(stemmed_words)
print(len(unique_words))
# now stemmed_words is my vocabulary

5656


In [91]:
# we can remove repeated by uning numpy 
a = np.array(stemmed_words)
u = np.unique(a)
print(u.shape)

(5656,)


In [94]:
# Now doing doing anything on text we need to convert it to numbers
# 4) Vectorization
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
# CountVectorizr = counts frequency

In [107]:
sample_text = ["I like movies , beautiful establishments and there were 200 people in the hall"]
# i want to vectorize each of my documents so i am going to use countVectorizer
# In count vectorizer . we can specify many things like stopwords , vocabulary , tokenizer , token_pattern but cant specify stemming
cv = CountVectorizer()
cv.fit_transform(sample_text).toarray()


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [108]:
cv.get_feature_names()

['200',
 'and',
 'beautiful',
 'establishments',
 'hall',
 'in',
 'like',
 'movies',
 'people',
 'the',
 'there',
 'were']

In [109]:
# Now we will give some parameters
sample_text = ["I like movies and like , beautiful establishments and there were 200 people in the hall . We played cricket yesterday"]
cv= CountVectorizer(stop_words = stop_words , token_pattern = "[A-Za-z]+")
cv.fit_transform(sample_text).toarray()

array([[1, 1, 1, 1, 2, 1, 1, 1, 1]], dtype=int64)

In [110]:
cv.get_feature_names()

['beautiful',
 'cricket',
 'establishments',
 'hall',
 'like',
 'movies',
 'people',
 'played',
 'yesterday']

In [111]:
# want to see vocabulary with index in features list
cv.vocabulary_

{'like': 4,
 'movies': 5,
 'beautiful': 0,
 'establishments': 2,
 'people': 6,
 'hall': 3,
 'played': 7,
 'cricket': 1,
 'yesterday': 8}

In [158]:
# everything is there in countVectorizer but stemming is not there , we need to do stemming manually
sample_text = ["I like movies and like , beautiful establishments and there were 200 people in the hall . We played cricket yesterday"]
cv = CountVectorizer(stop_words = stop_words , token_pattern = "[A-Za-z]+" , preprocessor = stemming2)

In [159]:
def stemming2(doc) :
    words = word_tokenize(doc)
    stemmer = PorterStemmer()
    st = ""
    for word in words :
        st += stemmer.stem(word) + " "
    return st


In [160]:
cv.fit_transform(sample_text).toarray()
print(cv.get_feature_names())
print(cv.vocabulary_)

['beauti', 'cricket', 'establish', 'hall', 'like', 'movi', 'peopl', 'play', 'yesterday']
{'like': 4, 'movi': 5, 'beauti': 0, 'establish': 2, 'peopl': 6, 'hall': 3, 'play': 7, 'cricket': 1, 'yesterday': 8}


D:\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'ani', 'becaus', 'befor', 'could', 'doe', 'dure', 'ha', 'hi', 'might', 'must', 'n', 'need', 'onc', 'onli', 'ourselv', 'sha', 'themselv', 'thi', 'veri', 'wa', 'whi', 'wo', 'would', 'yourselv'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '


In [165]:
# Tf Idf Vectorizer - Term frequence inverse document frequency vectorizer
# Terms (words) which are usually ca=oming are of less importance and should contribute less    
sample_text = ["I like movies and like" , "beautiful establishments and there were 200 people in the hall "," We played cricket yesterday"]
tfidf = TfidfVectorizer()
tfidf.fit_transform(sample_text).toarray()

array([[0.        , 0.32200242, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.84678897, 0.42339448, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.32311233, 0.24573525, 0.32311233, 0.        , 0.32311233,
        0.32311233, 0.32311233, 0.        , 0.        , 0.32311233,
        0.        , 0.32311233, 0.32311233, 0.        , 0.32311233,
        0.        ],
       [0.        , 0.        , 0.        , 0.5       , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.5       , 0.        , 0.        , 0.5       , 0.        ,
        0.5       ]])

In [168]:
# we can use ngram feature - pair me number liye jaenge
cv2 = CountVectorizer(ngram_range = (2,2) , stop_words =stop_words , token_pattern  = "[A-Za-z]+")
cv2.fit_transform(sample_text).toarray()

array([[0, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1]], dtype=int64)

In [169]:
cv2.get_feature_names()

['beautiful establishments',
 'cricket yesterday',
 'establishments people',
 'like movies',
 'movies like',
 'people hall',
 'played cricket']

In [171]:
cv2.vocabulary_

{'like movies': 3,
 'movies like': 4,
 'beautiful establishments': 0,
 'establishments people': 2,
 'people hall': 5,
 'played cricket': 6,
 'cricket yesterday': 1}

In [174]:
# 1 and 2 pair
cv3 = CountVectorizer(ngram_range = (1,2) , stop_words =stop_words , token_pattern  = "[A-Za-z]+")
cv3.fit_transform(sample_text).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]], dtype=int64)

In [175]:
cv3.get_feature_names()

['beautiful',
 'beautiful establishments',
 'cricket',
 'cricket yesterday',
 'establishments',
 'establishments people',
 'hall',
 'like',
 'like movies',
 'movies',
 'movies like',
 'people',
 'people hall',
 'played',
 'played cricket',
 'yesterday']

In [176]:
cv2.vocabulary_

{'like movies': 3,
 'movies like': 4,
 'beautiful establishments': 0,
 'establishments people': 2,
 'people hall': 5,
 'played cricket': 6,
 'cricket yesterday': 1}