In [6]:
import numpy as np

In [3]:
np.absolute(-4)

4

In [4]:
a = np.array([1 , 2 , 3, 4])
print(a)

[1 2 3 4]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a.shape

(4,)

In [7]:
b = np.array([[1 , 2, 3 , 4], [5 , 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
b.shape

(2, 4)

In [10]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
np.dot(b , b.T)

array([[ 30,  70],
       [ 70, 174]])

In [12]:
b.dot(b.T)

array([[ 30,  70],
       [ 70, 174]])

In [13]:
np.random.randint(60 , 80 , 10)

array([78, 64, 60, 73, 64, 75, 72, 69, 60, 75])

In [15]:
matrix = np.random.randint(60 , 80 , (5 , 5))
matrix

array([[63, 76, 71, 66, 78],
       [75, 67, 62, 67, 64],
       [73, 66, 63, 68, 78],
       [72, 70, 69, 69, 61],
       [60, 62, 63, 75, 77]])

In [16]:
np.max(matrix)

78

In [19]:
np.argmax(matrix[3])

0

In [20]:
a

array([1, 2, 3, 4])

In [31]:
a = np.array([0 , 1,1,8,10 ,2,-3,6,8,10])

In [32]:
np.argmin(a)

6

In [33]:
np.argmax(a)

4

In [34]:
a.mean()

4.3

In [35]:
np.unique(a)

array([-3,  0,  1,  2,  6,  8, 10])

In [36]:
np.unique(a , return_counts = True)

(array([-3,  0,  1,  2,  6,  8, 10]),
 array([1, 1, 2, 1, 1, 2, 2], dtype=int64))

In [37]:
## Program to find out the Number with largest frequency in the array
a = np.array([1, 6 , 1,0 , 1,1,8,10 ,2,-3,6,8,10])
b , c = np.unique(a , return_counts = True)

In [38]:
b[np.argmax(c)]

1

In [2]:
#Slicing 
matrix = [[63, 76, 71, 66, 78],
       [75, 67, 62, 67, 64],
       [73, 66, 63, 68, 78],
       [72, 70, 69, 69, 61],
       [60, 62, 63, 75, 77]]

In [4]:
type(matrix)

list

In [7]:
matrix = np.array(matrix)

In [9]:
matrix[2:4,1:4]

array([[66, 63, 68],
       [70, 69, 69]])